// Platform's own list RPCs, every request that carries a QueryFilter and every response that
// carries a Pagination. A product's list RPCs conform the same way, in the product.

extension Primandproper_Platform_Audit_V1_ListAnyEntriesRequest: ListRequest {}
extension Primandproper_Platform_Audit_V1_ListEntriesRequest: ListRequest {}
extension Primandproper_Platform_Billing_V1_ListCurrentSubscriptionsRequest: ListRequest {}
extension Primandproper_Platform_Billing_V1_ListProductsRequest: ListRequest {}
extension Primandproper_Platform_Billing_V1_ListPurchasesForAccountRequest: ListRequest {}
extension Primandproper_Platform_Billing_V1_ListPurchasesRequest: ListRequest {}
extension Primandproper_Platform_Billing_V1_ListSubscriptionsForAccountRequest: ListRequest {}
extension Primandproper_Platform_Billing_V1_ListSubscriptionsRequest: ListRequest {}
extension Primandproper_Platform_Billing_V1_ListTransactionsForAccountRequest: ListRequest {}
extension Primandproper_Platform_Billing_V1_ListTransactionsRequest: ListRequest {}
extension Primandproper_Platform_Comments_V1_ListCommentsByAuthorRequest: ListRequest {}
extension Primandproper_Platform_Comments_V1_ListCommentsByTargetTypeRequest: ListRequest {}
extension Primandproper_Platform_Comments_V1_ListRepliesRequest: ListRequest {}
extension Primandproper_Platform_Comments_V1_ListRootCommentsRequest: ListRequest {}
extension Primandproper_Platform_Identity_V1_ListAccountMembersRequest: ListRequest {}
extension Primandproper_Platform_Identity_V1_ListAccountsForUserRequest: ListRequest {}
extension Primandproper_Platform_Identity_V1_ListAccountsRequest: ListRequest {}
extension Primandproper_Platform_Identity_V1_ListInvitationsForEmailAddressRequest: ListRequest {}
extension Primandproper_Platform_Identity_V1_ListInvitationsFromUserRequest: ListRequest {}
extension Primandproper_Platform_Identity_V1_ListUsersRequest: ListRequest {}
extension Primandproper_Platform_Identity_V1_SearchUsersByUsernameRequest: ListRequest {}
extension Primandproper_Platform_Issuereports_V1_ListReportsAcrossScopesRequest: ListRequest {}
extension Primandproper_Platform_Issuereports_V1_ListReportsByReporterRequest: ListRequest {}
extension Primandproper_Platform_Issuereports_V1_ListReportsByStatusAcrossScopesRequest: ListRequest
{}
extension Primandproper_Platform_Issuereports_V1_ListReportsByStatusRequest: ListRequest {}
extension Primandproper_Platform_Issuereports_V1_ListReportsBySubjectTypeRequest: ListRequest {}
extension Primandproper_Platform_Issuereports_V1_ListReportsForSubjectRequest: ListRequest {}
extension Primandproper_Platform_Issuereports_V1_ListReportsRequest: ListRequest {}
extension Primandproper_Platform_Mediaregistry_V1_ListMyObjectsRequest: ListRequest {}
extension Primandproper_Platform_Mediaregistry_V1_ListObjectsBySubjectRequest: ListRequest {}
extension Primandproper_Platform_Notifications_V1_ListDevicesRequest: ListRequest {}
extension Primandproper_Platform_Notifications_V1_ListNotificationsRequest: ListRequest {}
extension Primandproper_Platform_Notifications_V1_ListUnreadNotificationsRequest: ListRequest {}
extension Primandproper_Platform_Oauth2clients_V1_ListOAuth2ClientsRequest: ListRequest {}
extension Primandproper_Platform_Settings_V1_ListDefinitionsRequest: ListRequest {}
extension Primandproper_Platform_Settings_V1_ListValuesForDefinitionRequest: ListRequest {}
extension Primandproper_Platform_Settings_V1_ListValuesForSubjectRequest: ListRequest {}
extension Primandproper_Platform_Waitlists_V1_ListListsRequest: ListRequest {}
extension Primandproper_Platform_Waitlists_V1_ListOpenListsRequest: ListRequest {}
extension Primandproper_Platform_Waitlists_V1_ListSignupsForSubjectRequest: ListRequest {}
extension Primandproper_Platform_Waitlists_V1_ListSignupsRequest: ListRequest {}
extension Primandproper_Platform_Webhooks_V1_ListAttemptsRequest: ListRequest {}
extension Primandproper_Platform_Webhooks_V1_ListEndpointsRequest: ListRequest {}
extension Primandproper_Platform_Webhooks_V1_ListSubscriptionsRequest: ListRequest {}

extension Primandproper_Platform_Audit_V1_ListAnyEntriesResponse: ListResponse {}
extension Primandproper_Platform_Audit_V1_ListEntriesResponse: ListResponse {}
extension Primandproper_Platform_Billing_V1_ListCurrentSubscriptionsResponse: ListResponse {}
extension Primandproper_Platform_Billing_V1_ListProductsResponse: ListResponse {}
extension Primandproper_Platform_Billing_V1_ListPurchasesForAccountResponse: ListResponse {}
extension Primandproper_Platform_Billing_V1_ListPurchasesResponse: ListResponse {}
extension Primandproper_Platform_Billing_V1_ListSubscriptionsForAccountResponse: ListResponse {}
extension Primandproper_Platform_Billing_V1_ListSubscriptionsResponse: ListResponse {}
extension Primandproper_Platform_Billing_V1_ListTransactionsForAccountResponse: ListResponse {}
extension Primandproper_Platform_Billing_V1_ListTransactionsResponse: ListResponse {}
extension Primandproper_Platform_Comments_V1_ListCommentsByAuthorResponse: ListResponse {}
extension Primandproper_Platform_Comments_V1_ListCommentsByTargetTypeResponse: ListResponse {}
extension Primandproper_Platform_Comments_V1_ListRepliesResponse: ListResponse {}
extension Primandproper_Platform_Comments_V1_ListRootCommentsResponse: ListResponse {}
extension Primandproper_Platform_Identity_V1_ListAccountMembersResponse: ListResponse {}
extension Primandproper_Platform_Identity_V1_ListAccountsForUserResponse: ListResponse {}
extension Primandproper_Platform_Identity_V1_ListAccountsResponse: ListResponse {}
extension Primandproper_Platform_Identity_V1_ListInvitationsForEmailAddressResponse: ListResponse {}
extension Primandproper_Platform_Identity_V1_ListInvitationsFromUserResponse: ListResponse {}
extension Primandproper_Platform_Identity_V1_ListUsersResponse: ListResponse {}
extension Primandproper_Platform_Identity_V1_SearchUsersByUsernameResponse: ListResponse {}
extension Primandproper_Platform_Issuereports_V1_ListReportsAcrossScopesResponse: ListResponse {}
extension Primandproper_Platform_Issuereports_V1_ListReportsByReporterResponse: ListResponse {}
extension Primandproper_Platform_Issuereports_V1_ListReportsByStatusAcrossScopesResponse:
  ListResponse
{}
extension Primandproper_Platform_Issuereports_V1_ListReportsByStatusResponse: ListResponse {}
extension Primandproper_Platform_Issuereports_V1_ListReportsBySubjectTypeResponse: ListResponse {}
extension Primandproper_Platform_Issuereports_V1_ListReportsForSubjectResponse: ListResponse {}
extension Primandproper_Platform_Issuereports_V1_ListReportsResponse: ListResponse {}
extension Primandproper_Platform_Mediaregistry_V1_ListMyObjectsResponse: ListResponse {}
extension Primandproper_Platform_Mediaregistry_V1_ListObjectsBySubjectResponse: ListResponse {}
extension Primandproper_Platform_Notifications_V1_ListDevicesResponse: ListResponse {}
extension Primandproper_Platform_Notifications_V1_ListNotificationsResponse: ListResponse {}
extension Primandproper_Platform_Notifications_V1_ListUnreadNotificationsResponse: ListResponse {}
extension Primandproper_Platform_Oauth2clients_V1_ListOAuth2ClientsResponse: ListResponse {}
extension Primandproper_Platform_Settings_V1_ListDefinitionsResponse: ListResponse {}
extension Primandproper_Platform_Settings_V1_ListValuesForDefinitionResponse: ListResponse {}
extension Primandproper_Platform_Settings_V1_ListValuesForSubjectResponse: ListResponse {}
extension Primandproper_Platform_Waitlists_V1_ListListsResponse: ListResponse {}
extension Primandproper_Platform_Waitlists_V1_ListOpenListsResponse: ListResponse {}
extension Primandproper_Platform_Waitlists_V1_ListSignupsForSubjectResponse: ListResponse {}
extension Primandproper_Platform_Waitlists_V1_ListSignupsResponse: ListResponse {}
extension Primandproper_Platform_Webhooks_V1_ListAttemptsResponse: ListResponse {}
extension Primandproper_Platform_Webhooks_V1_ListEndpointsResponse: ListResponse {}
extension Primandproper_Platform_Webhooks_V1_ListSubscriptionsResponse: ListResponse {}
