#!/usr/bin/env bash
# Generate the ListRequest and ListResponse conformances for every generated message that has
# the shape: a request with a QueryFilter `filter`, a response with a Pagination `pagination`
# and a repeated `results`. It reads protoc's output rather than the .proto sources so that
# it runs without a fetch, and generate.sh runs it last so that CI's regeneration check
# covers this file as well.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GENERATED="$ROOT/Sources/PlatformClient/Generated"
OUT="$GENERATED/ListConformances.swift"

# The $ in the program is awk's, not the shell's.
# shellcheck disable=SC2016
find "$GENERATED" -name '*.pb.swift' | sort | xargs awk '
  /^public struct [A-Za-z0-9_]+: / {
    name = $3
    sub(/:$/, "", name)
    filter = pagination = results = 0
    next
  }
  name != "" && /^  public var filter: Primandproper_Platform_Filtering_V1_QueryFilter / { filter = 1 }
  name != "" && /^  public var pagination: Primandproper_Platform_Filtering_V1_Pagination / { pagination = 1 }
  name != "" && /^  public var results: \[/ { results = 1 }
  name != "" && /^}/ {
    if (filter) print "extension " name ": ListRequest {}"
    if (pagination && results) print "extension " name ": ListResponse {}"
    name = ""
  }
' | sort >"$OUT.body"

{
  echo "// Generated by scripts/generate-list-conformances.sh. DO NOT EDIT."
  echo "//"
  echo "// Every platform request that carries a QueryFilter and every response that carries a"
  echo "// Pagination and its rows. A product's list RPCs conform the same way, in the product."
  echo
  cat "$OUT.body"
} >"$OUT"
rm "$OUT.body"

echo "generated $(grep -c '^extension' "$OUT") list conformances -> ${OUT#"$ROOT"/}"
